version: "3.7"

services:

  nodejs:
    build:
      context: .
      args:
        - version=12.14.0
        - build=dev
    image: leadstec/nodejs:12.14.0
    ports:
      - "50401:3000"
    volumes:
      - ~/volumes/nodejs.local/log:/data/log
      - ~/volumes/nodejs.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
      - NODE_ENV=development
    secrets:
      - lcs
    hostname: nodejs.local
    container_name: nodejs.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
